apiVersion: apps/v1
kind: Deployment
metadata:
   name: GoMyCode-deployment
   labels:
      app: myapp
      type: front-end
sepc:
   template:
      metadata:
         name: myapp-pod
         labels:
            app: myapp
            type: front-end
      spec:
         containers:
         -  name: GoMyCode-container
            image: bensmaileya/eya-app
   replicas: 4
   selector:
      matchLabels:
         type: front-end
