apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: GoMyCode-replicaset
   labels:
      app: myapp
      type: front-end
sepc:
   template:
      metadata:
         name: myapp-pod
         labels:
            app: myapp
            type: front-end
      spec:
         containers:
         -  name: DockerTesting-container
            image: DockerTesting
   replicas: 4
   selector:
      matchLabels:
         type: front-end
