apiVersion: v1
kind: Service
metadata:
   name: GoMyCode-service
sepc:
   type: NodePort
   ports:
      - targetPort: 80
        port: 80
        nodePort: 30008
   selector:
      app: myapp-pod
      type: front-end
